---
title: "Portfolio"
author: "Michael Okyere"
date: "10-2-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(spotifyr)
```   

```{r Create Corpus, eval = FALSE, echo = FALSE}
#Read filenames of csv's
files <- list.files(path="csvPlaylists/", pattern="week+.*csv")

#Create list of data frame per week without the ".csv" part 
weeks <- substr(files,1,nchar(files)-4)

#Load all files in a loop using weeks data frame 
for(i in weeks){
    filepath <- file.path("csvPlaylists",paste(i,".csv",sep=""))
    #assign csv to variable df
    df <- read.csv(filepath)
    #clean data frame: remove header, set 1st row as header, remove 1st row
    names(df) <- NULL 
    names(df) <- df[1,] 
    df <- df[-1,]
    #Select first 50 values (Top 50) of df 
    df <- head(df,50)
    #Loop-in-loop: for each week in df
    for(j in df){
        #Set variables to correct datatype
        df$Position <- as.integer(as.character(df$Position))
        df$Streams <- as.integer(as.character(df$Streams))
        #Extract Spotify URI from URL
        df$URI <- str_replace(df$URL, "https://open.spotify.com/track/", "")
        #Create variable "week*_20**" and assign current df
        assign(paste0("", i), df)
        #Create variable "featuresweek*_20**" and assign Spotify audiofeatures
        assign(paste0("features", i),get_track_audio_features(df$URI))
    }
}
```

